### ISSUE TITLE
File icons in pull requests and commit screens

### ISSUE THREAD

**Issue by crazyoptimist** [homerchen19/github-file-icons#118]
Thank you for your great work!
Hope you can add terraform file icons as well.
Cheers!

**Comment by CrazyOptimist** [comment]
Oh that's weird, it's already supported, never mind.  

But in the improved github UI(improved pull request/commit screen, see the attached image), it doesn't show up icons at all for any kind of files.

![image](https://user-images.githubusercontent.com/55074937/173519501-1a217510-7e6e-4f27-ae5b-9cf028ec7f66.png)

**Comment by homerchen19** [comment]
It works on my Chrome.

<img width="341" alt="Screen Shot 2022-06-24 at 10 48 49" src="https://user-images.githubusercontent.com/12113222/175455225-06e6d9ff-f66e-4f14-b37a-c8783065e647.png">

Are you using Firefox? If so, it may be caused by https://github.com/homerchen19/github-file-icons/issues/117. I just fixed it, could you try again later?

**Comment by crazyoptimist** [comment]
I use the latest version of chrome, and that's weird. I removed the extension and reinstalled, but it still persists:
![image](https://user-images.githubusercontent.com/55074937/175477243-159f9210-9cb1-4394-b5eb-f5ed2092596a.png)

**Comment by homerchen19** [comment]
hmm could you provide the URL of that PR? I can check if it works on my side.

**Comment by crazyoptimist** [comment]
https://github.com/crazyoptimist/terraform-basecamp/pull/1

**Comment by homerchen19** [comment]
Well it works on my Chrome. Maybe you can turn off other extensions just in case there are some conflicts?

<img width="356" alt="Screen Shot 2022-06-25 at 23 43 23" src="https://user-images.githubusercontent.com/12113222/175780894-5977efa6-1172-4471-9358-7e76306046e9.png">

**Comment by crazyoptimist** [comment]
Oh that's super weird. I disabled adblocker extension(the only one I'm using except for yours) and tried again, but the same thing happens. Anyways,  if it's only me, can close this issue. Never mind.
Thanks!
